title: About me - Krystian Warda
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: https://twitter.com/krystianwarda #if your site has a twitter account, enter it here

# Author Settings
author: Krystian Warda # add your name
author-img: krystian-warda.jpg # add your photo
about-author: I am a Engineer. Career Shifter from Construction Engineering forward Data Science and Programming. # add description
social-twitter: krystianwarda # add your Twitter handle
social-github: krystianwarda # add your Github handle
social-linkedin: krystian-warda-559391144 # add your Linkedin handle
social-email: krystian.warda@gmail.com # add your Email address

# Disqus
discus-identifier: datwardaguy # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
